# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/epi/PycharmProjects/imagedisplay/htmap/htmap_ui4.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 553)
        MainWindow.setMouseTracking(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.layers = QtWidgets.QTreeWidget(self.splitter_3)
        self.layers.setObjectName("layers")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setMouseTracking(True)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setMouseTracking(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.mapBox = QtWidgets.QGroupBox(self.splitter)
        self.mapBox.setMouseTracking(True)
        self.mapBox.setTitle("")
        self.mapBox.setObjectName("mapBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mapBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.webEngineView_map = QtWebEngineWidgets.QWebEngineView(self.mapBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webEngineView_map.sizePolicy().hasHeightForWidth())
        self.webEngineView_map.setSizePolicy(sizePolicy)
        self.webEngineView_map.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.webEngineView_map.setMouseTracking(True)
        self.webEngineView_map.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.webEngineView_map.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView_map.setObjectName("webEngineView_map")
        self.gridLayout.addWidget(self.webEngineView_map, 0, 0, 2, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.markerBox = QtWidgets.QGroupBox(self.splitter)
        self.markerBox.setTitle("")
        self.markerBox.setObjectName("markerBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.markerBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.markerLayout = QtWidgets.QGridLayout()
        self.markerLayout.setObjectName("markerLayout")
        self.newclass = QtWidgets.QLineEdit(self.markerBox)
        self.newclass.setObjectName("newclass")
        self.markerLayout.addWidget(self.newclass, 2, 0, 1, 1)
        self.marker_description_label = QtWidgets.QLabel(self.markerBox)
        self.marker_description_label.setObjectName("marker_description_label")
        self.markerLayout.addWidget(self.marker_description_label, 3, 0, 1, 1)
        self.markerclassLayout = QtWidgets.QHBoxLayout()
        self.markerclassLayout.setObjectName("markerclassLayout")
        self.marker_class_label = QtWidgets.QLabel(self.markerBox)
        self.marker_class_label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.marker_class_label.setObjectName("marker_class_label")
        self.markerclassLayout.addWidget(self.marker_class_label)
        self.marker_type = QtWidgets.QComboBox(self.markerBox)
        self.marker_type.setObjectName("marker_type")
        self.marker_type.addItem("")
        self.marker_type.addItem("")
        self.markerclassLayout.addWidget(self.marker_type)
        self.addclass = QtWidgets.QToolButton(self.markerBox)
        self.addclass.setObjectName("addclass")
        self.markerclassLayout.addWidget(self.addclass)
        self.markerLayout.addLayout(self.markerclassLayout, 1, 0, 1, 1)
        self.markerdescriptionScrollArea = QtWidgets.QScrollArea(self.markerBox)
        self.markerdescriptionScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.markerdescriptionScrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.markerdescriptionScrollArea.setLineWidth(0)
        self.markerdescriptionScrollArea.setWidgetResizable(True)
        self.markerdescriptionScrollArea.setObjectName("markerdescriptionScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 160, 340))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.markerScrollAreaLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.markerScrollAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.markerScrollAreaLayout.setObjectName("markerScrollAreaLayout")
        self.textEditortoolsLayout = QtWidgets.QHBoxLayout()
        self.textEditortoolsLayout.setObjectName("textEditortoolsLayout")
        self.toolButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.textEditortoolsLayout.addWidget(self.toolButton)
        self.makelink = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.makelink.setText("")
        self.makelink.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.makelink.setObjectName("makelink")
        self.textEditortoolsLayout.addWidget(self.makelink)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.textEditortoolsLayout.addItem(spacerItem1)
        self.markerScrollAreaLayout.addLayout(self.textEditortoolsLayout)
        self.marker_description = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.marker_description.setObjectName("marker_description")
        self.markerScrollAreaLayout.addWidget(self.marker_description)
        self.markerdescriptionScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.markerLayout.addWidget(self.markerdescriptionScrollArea, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.markerLayout)
        self.sedimentBox = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sedimentBox.sizePolicy().hasHeightForWidth())
        self.sedimentBox.setSizePolicy(sizePolicy)
        self.sedimentBox.setTitle("")
        self.sedimentBox.setObjectName("sedimentBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sedimentBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hide = QtWidgets.QToolButton(self.sedimentBox)
        self.hide.setObjectName("hide")
        self.horizontalLayout.addWidget(self.hide)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.decreaseCS = QtWidgets.QToolButton(self.sedimentBox)
        self.decreaseCS.setAutoRepeat(True)
        self.decreaseCS.setObjectName("decreaseCS")
        self.horizontalLayout.addWidget(self.decreaseCS)
        self.increaseCS = QtWidgets.QToolButton(self.sedimentBox)
        self.increaseCS.setAutoRepeat(True)
        self.increaseCS.setObjectName("increaseCS")
        self.horizontalLayout.addWidget(self.increaseCS)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.sedimentBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 244, 375))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shepardframeB = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shepardframeB.sizePolicy().hasHeightForWidth())
        self.shepardframeB.setSizePolicy(sizePolicy)
        self.shepardframeB.setMinimumSize(QtCore.QSize(100, 100))
        self.shepardframeB.setMaximumSize(QtCore.QSize(400, 400))
        self.shepardframeB.setStyleSheet("QFrame { border: white }")
        self.shepardframeB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shepardframeB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shepardframeB.setObjectName("shepardframeB")
        self.horizontalLayout_2.addWidget(self.shepardframeB)
        self.shepardframeA = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shepardframeA.sizePolicy().hasHeightForWidth())
        self.shepardframeA.setSizePolicy(sizePolicy)
        self.shepardframeA.setMinimumSize(QtCore.QSize(100, 100))
        self.shepardframeA.setMaximumSize(QtCore.QSize(400, 400))
        self.shepardframeA.setStyleSheet("QFrame { border: white }")
        self.shepardframeA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shepardframeA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shepardframeA.setObjectName("shepardframeA")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.shepardframeA)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addWidget(self.shepardframeA)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.folkframeB = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.folkframeB.setMinimumSize(QtCore.QSize(100, 100))
        self.folkframeB.setMaximumSize(QtCore.QSize(400, 400))
        self.folkframeB.setStyleSheet("QFrame { border: white }")
        self.folkframeB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folkframeB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folkframeB.setObjectName("folkframeB")
        self.horizontalLayout_4.addWidget(self.folkframeB)
        self.folkframeA = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folkframeA.sizePolicy().hasHeightForWidth())
        self.folkframeA.setSizePolicy(sizePolicy)
        self.folkframeA.setMinimumSize(QtCore.QSize(100, 100))
        self.folkframeA.setMaximumSize(QtCore.QSize(400, 400))
        self.folkframeA.setStyleSheet("QFrame { border: white }")
        self.folkframeA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folkframeA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folkframeA.setObjectName("folkframeA")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.folkframeA)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4.addWidget(self.folkframeA)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.horizontalLayout_6.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuMap = QtWidgets.QMenu(self.menuView)
        self.menuMap.setObjectName("menuMap")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuGRASS = QtWidgets.QMenu(self.menuSettings)
        self.menuGRASS.setObjectName("menuGRASS")
        self.menuAnnotation = QtWidgets.QMenu(self.menubar)
        self.menuAnnotation.setObjectName("menuAnnotation")
        self.menuSediment_Classification = QtWidgets.QMenu(self.menuAnnotation)
        self.menuSediment_Classification.setObjectName("menuSediment_Classification")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuProcessing = QtWidgets.QMenu(self.menubar)
        self.menuProcessing.setObjectName("menuProcessing")
        self.menuSurface_Analysis = QtWidgets.QMenu(self.menuProcessing)
        self.menuSurface_Analysis.setObjectName("menuSurface_Analysis")
        self.menuLandform_Extraction = QtWidgets.QMenu(self.menuSurface_Analysis)
        self.menuLandform_Extraction.setObjectName("menuLandform_Extraction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAddmarker = QtWidgets.QAction(MainWindow)
        self.actionAddmarker.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/blumarker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddmarker.setIcon(icon)
        self.actionAddmarker.setObjectName("actionAddmarker")
        self.actionHtmlExport = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/HTML5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHtmlExport.setIcon(icon1)
        self.actionHtmlExport.setObjectName("actionHtmlExport")
        self.action2D = QtWidgets.QAction(MainWindow)
        self.action2D.setObjectName("action2D")
        self.action3D = QtWidgets.QAction(MainWindow)
        self.action3D.setObjectName("action3D")
        self.actionShepard = QtWidgets.QAction(MainWindow)
        self.actionShepard.setObjectName("actionShepard")
        self.actionFolk = QtWidgets.QAction(MainWindow)
        self.actionFolk.setObjectName("actionFolk")
        self.actionBiotope = QtWidgets.QAction(MainWindow)
        self.actionBiotope.setObjectName("actionBiotope")
        self.actionGRASS_Envs = QtWidgets.QAction(MainWindow)
        self.actionGRASS_Envs.setObjectName("actionGRASS_Envs")
        self.actionSegmentation = QtWidgets.QAction(MainWindow)
        self.actionSegmentation.setObjectName("actionSegmentation")
        self.actionQuantitative_Geometry = QtWidgets.QAction(MainWindow)
        self.actionQuantitative_Geometry.setObjectName("actionQuantitative_Geometry")
        self.actionGeomorphometry = QtWidgets.QAction(MainWindow)
        self.actionGeomorphometry.setObjectName("actionGeomorphometry")
        self.actionSurface_Generation = QtWidgets.QAction(MainWindow)
        self.actionSurface_Generation.setObjectName("actionSurface_Generation")
        self.actionsedimentclass = QtWidgets.QAction(MainWindow)
        self.actionsedimentclass.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/geology-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsedimentclass.setIcon(icon2)
        self.actionsedimentclass.setObjectName("actionsedimentclass")
        self.cmecs = QtWidgets.QAction(MainWindow)
        self.cmecs.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/CMECS-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmecs.setIcon(icon3)
        self.cmecs.setObjectName("cmecs")
        self.menuMap.addAction(self.action2D)
        self.menuMap.addAction(self.action3D)
        self.menuView.addAction(self.menuMap.menuAction())
        self.menuGRASS.addAction(self.actionGRASS_Envs)
        self.menuSettings.addAction(self.menuGRASS.menuAction())
        self.menuSediment_Classification.addAction(self.actionShepard)
        self.menuSediment_Classification.addAction(self.actionFolk)
        self.menuAnnotation.addAction(self.menuSediment_Classification.menuAction())
        self.menuAnnotation.addAction(self.actionBiotope)
        self.menuLandform_Extraction.addAction(self.actionQuantitative_Geometry)
        self.menuLandform_Extraction.addAction(self.actionGeomorphometry)
        self.menuSurface_Analysis.addAction(self.menuLandform_Extraction.menuAction())
        self.menuSurface_Analysis.addAction(self.actionSurface_Generation)
        self.menuProcessing.addAction(self.actionSegmentation)
        self.menuProcessing.addAction(self.menuSurface_Analysis.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuAnnotation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAddmarker)
        self.toolBar.addAction(self.actionsedimentclass)
        self.toolBar.addAction(self.cmecs)
        self.toolBar.addAction(self.actionHtmlExport)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.layers.headerItem().setText(0, _translate("MainWindow", "Layers"))
        self.marker_description_label.setText(_translate("MainWindow", "Description"))
        self.marker_class_label.setText(_translate("MainWindow", "Class"))
        self.marker_type.setItemText(0, _translate("MainWindow", "cities"))
        self.marker_type.setItemText(1, _translate("MainWindow", "caves"))
        self.addclass.setText(_translate("MainWindow", "+"))
        self.makelink.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/icons/blumarker.png\"/></p></body></html>"))
        self.marker_description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.google.no/search?q=qtextedit+get+text&amp;oq=qtext&amp;aqs=chrome.2.0j69i57j0l4.3735j0j4&amp;sourceid=chrome&amp;ie=UTF-8#q=qtextedit+get+text+python\"><span style=\" text-decoration: underline; color:#0000ff;\">title</span></a></p></body></html>"))
        self.hide.setText(_translate("MainWindow", "H"))
        self.decreaseCS.setText(_translate("MainWindow", "-"))
        self.increaseCS.setText(_translate("MainWindow", "+"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuGRASS.setTitle(_translate("MainWindow", "GRASS"))
        self.menuAnnotation.setTitle(_translate("MainWindow", "Annotation"))
        self.menuSediment_Classification.setTitle(_translate("MainWindow", "Sediment Classification"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing"))
        self.menuSurface_Analysis.setTitle(_translate("MainWindow", "Surface Analysis"))
        self.menuLandform_Extraction.setTitle(_translate("MainWindow", "Landform Extraction"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAddmarker.setText(_translate("MainWindow", "addmarker"))
        self.actionAddmarker.setToolTip(_translate("MainWindow", "Add Marker"))
        self.actionHtmlExport.setText(_translate("MainWindow", "htmlExport"))
        self.actionHtmlExport.setToolTip(_translate("MainWindow", "Export map widget to HTML"))
        self.action2D.setText(_translate("MainWindow", "2D"))
        self.action3D.setText(_translate("MainWindow", "3D"))
        self.actionShepard.setText(_translate("MainWindow", "Shepard"))
        self.actionFolk.setText(_translate("MainWindow", "Folk"))
        self.actionBiotope.setText(_translate("MainWindow", "Biotope"))
        self.actionGRASS_Envs.setText(_translate("MainWindow", "GRASS Envs"))
        self.actionSegmentation.setText(_translate("MainWindow", "Segmentation"))
        self.actionQuantitative_Geometry.setText(_translate("MainWindow", "Quantitative Geometry"))
        self.actionGeomorphometry.setText(_translate("MainWindow", "Geomorphometry"))
        self.actionSurface_Generation.setText(_translate("MainWindow", "Surface Generation"))
        self.actionsedimentclass.setText(_translate("MainWindow", "sedimentclass"))
        self.actionsedimentclass.setToolTip(_translate("MainWindow", "chose sediment class"))
        self.cmecs.setText(_translate("MainWindow", "cmecs"))
        self.cmecs.setToolTip(_translate("MainWindow", "CMECS Coastal and Marine Ecosystem Classification Standard "))

from PyQt5 import QtWebEngineWidgets
import resources_rc
